# Generated by Django 5.2 on 2026-06-26 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBoleta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('periodo_referencia', models.CharField(max_length=64)),
                ('archivo', models.FileField(upload_to='boletas/')),
                ('valor_extraido', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Procesado', 'Procesado'), ('Pendiente', 'Pendiente'), ('Error', 'Error')], default='Pendiente', max_length=16)),
            ],
        ),
    ]
