# Generated by Django 5.2 on 2026-06-30 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroboleta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registroboleta',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='registroboleta',
            name='mensaje_procesamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroboleta',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroboleta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroboleta',
            name='valor_extraido',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
