# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_correccionboleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroboleta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='boletas/'),
        ),
        migrations.AddField(
            model_name='registroboleta',
            name='origen',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Boleta', 'Boleta')], default='Boleta', max_length=16),
        ),
    ]
