# Generated by Django 6.0.6 on 2026-08-28 02:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_manual_registros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('alcance', models.PositiveSmallIntegerField(choices=[(1, 'Alcance 1 - Directas'), (2, 'Alcance 2 - Energía importada'), (3, 'Alcance 3 - Indirectas')])),
                ('unidad_actividad', models.CharField(help_text='Unidad del dato de actividad, ej. kWh, litros, kg', max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de emisión',
                'verbose_name_plural': 'Categorías de emisión',
                'ordering': ['alcance', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='correccionboleta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FactorEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('valor_kg_co2e', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unidad', models.CharField(help_text='ej. kg CO2e / kWh', max_length=40)),
                ('fuente', models.CharField(max_length=255)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factores', to='auditoria.categoriaemision')),
            ],
            options={
                'verbose_name': 'Factor de emisión',
                'verbose_name_plural': 'Factores de emisión',
                'ordering': ['categoria', '-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text="Formato 'YYYY-MM'", max_length=7)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('ocr', 'OCR')], default='manual', max_length=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='auditoria.categoriaemision')),
                ('fuente_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='auditoria.registroboleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-periodo', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CalculoEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_kg_co2e', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos', to='auditoria.factoremision')),
                ('registro_actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo', to='auditoria.registroactividad')),
            ],
            options={
                'verbose_name': 'Cálculo de emisión',
                'verbose_name_plural': 'Cálculos de emisión',
            },
        ),
    ]
